apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: open-bluemix-reporting-pod
spec:
  replicas: 1
  template:
    metadata:
      name: open-bluemix-reporting-pod
      labels:
        run: open-bluemix-reporting
    spec:
      containers:
        - name: open-bluemix-dashboard
          image: dashboard
          env:
          - name: db_username
            value: admin
          - name: db_password
            value: TRUXKBBXPSSKKVXB
          - name: db_host
            value: opengrp-prod-par01-c00-1.compose.direct
          - name: db_port
            value: "15125"
          - name : db_database
            value: compose
          - name: db_adapter
            value: postgresql
          - name: db_encoding
            value: utf8
          - name: BX_LOGIN
            value: frederic.duport@open-groupe.com
          - name:  BX_PASSWORD
            value: IF1VNFuOm=BoS
          - name:  BX_SLEEP
            value: "21600"
          - name: MAIL_SENDER
            value: openbluemix@gmail.com
          - name: MAIL_SENDER_PW
            value: cba654321
          - name: VCAP_SERVICES_COMPOSE_FOR_POSTGRESQL_0_CREDENTIALS_URI
            value: postgres://admin:TRUXKBBXPSSKKVXB@opengrp-prod-par01-c00-1.compose.direct:15125/compose

          volumeMounts:
           - mountPath: /opt/service-bind
             name: service-bind-volume
      volumes:
        - name: service-bind-volume
          secret:
            defaultMode: 420
            secretName: binding-compose-postgres

---
apiVersion: v1
kind: Service
metadata:
  name: open-bluemix-reporting-service
  labels:
    run: open-bluemix-reporting
spec:
  type: NodePort
  selector:
    run: open-bluemix-reporting
  ports:
   - protocol: TCP
     port: 80
     nodePort: 32000
